name: php-env_project
services:
  composer:
    image: composer:latest
    container_name: composer
    depends_on:
      - php
    volumes:
      - .:/app
    networks:
      - php_network
    command: composer install --ignore-platform-reqs

  mysql:
    image: mysql:8.4
    container_name: mysql-8.4
    volumes:
      - php-env-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    networks:
      - php_network

  nginx:
    image: nginx:1.27-alpine3.21
    container_name: nginx_server127
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - '80:80'
    networks:
      - php_network
      
  php:
    build:
      context: docker/php
    container_name: php84
    volumes:
      - .:/var/www/html
    networks:
      - php_network

networks:
  php_network:
    driver: bridge
    name: php_network

volumes:
  php-env-mysql:
    driver: local
